### ISSUE TITLE
Not compatible with latest Nano S firmware 1.6

### ISSUE THREAD

**Issue by wkaluza** [LedgerHQ/app-passwords#24]
After upgrading to the latest firmware version 1.6 on Nano S, typing in a password via USB no longer works. Attempting to type a password produces no characters on the host; a second attempt freezes the Ledger device (buttons unresponsive, still no password) and requires a replug.

**Comment by pydlv** [comment]
Disappointing to see Ledger failing to respond to this issue.

**Comment by wkaluza** [comment]
I find this pretty shocking how lethargic the whole LedgerHQ GitHub organisation is. The upgrade of the SDK to v1.6 happened via a big-bang merge after a long period of inactivity, suggesting that it is a facade repo, and the real work happens elsewhere. Not great for transparency. Commit history shows that in the merge a file that is still referenced elsewhere was deleted, which resulted in at least one module becoming impossible to build. How was this not caught by build automation? Said automation clearly exists, since Ledger bothered to implement ways to programmatically seed a ledger device, disable PIN requests etc., which are clearly features to support system tests. Utility and build scripts inconsistently use `python` and `python3`, meaning that one needs to hack them or install the PyPI package on both Python 2.x and Python 3.x to work effectively. Issues and pull requests are seemingly ignored.

Regarding this issue in particular, I built the password manager from source (which is harder than it should be, as it tries to build and link to the aforementioned unbuildable module). I managed to upload it to a test Nano S and investigate the issue some more. It appears that this app relies on the function `ux_check_status` being called by the SDK, which v1.6 does not do, even though the previous version did. I understand the password manager is an alpha version, but either the original was misusing the previous SDK, or the merge which produced SDK v1.6 broke a pre-existing invariant (which should be documented). All this is pretty hard to discern, because the changes between SDK v1.5.x and v 1.6 are also tied up with apparent efforts to unify the Nano S and Nano X SDK, and introduce a new UI framework called Flow. The docs are not in step with the changes. All this paints a messy picture.

Honestly, that's all the unpaid work that I'm prepared to do for a company which is big enough to know better.

Ledger... are you ok? All of the above issues are routine matters of workflow and best practice that have been solved by devs the world over (yes, also embedded devs). This password manager app is extremely useful, and all non-cryptocurrency related hardware password vaults/generators out there have serious UX or security flaws. It would be nice if this was shown some TLC; otherwise you're just making yourselves difficult to trust.

**Comment by zimlokks** [comment]
I've had this issue before. It's usually a USB cable issue.no idea why, but Ive had issues with the cables supplied by Ledger, at least some cables.

I'm updated to 1.6 on the Nano S and my password manager works flawlessly. My laptop is running Ubuntu 19.10, the Nano S connected to a USB 3.0 port. 

The password manager holds my disk decryption password and 2FA to login in the actual account.

Seriously it's usually a cable issue.

**Comment by pydlv** [comment]
One of the Ledger mods responded to my Reddit thread saying that the password typing still works on Linux and Mac OS X, which it sounds like zimlokks may have confirmed.

I completely agree with wkaluza and I don't understand why they can't integrate testing of their apps into their workflow to ensure things don't break. It is a pretty standard thing to do.

**Comment by pydlv** [comment]
Also per the same Reddit mod, this seems to be a problem with Windows and not any specific firmware or Ledger update. Be this as it may, I still don't feel that it's any excuse for not responding to users for months on end when they tell you things are broken.

**Comment by wkaluza** [comment]
Not a cable problem in my case - that was the first thing I checked. Tried two old and trusty cables as well as the Ledger-supplied cable one I normally use. No change in behaviour, the device freezes. All three cables work with the password manager app on my second Nano S, which I didn't upgrade. The Ledger cable worked fine with password manager on my primary Nano S until the firmware upgrade. Besides, all other apps (BTC, XTZ, ETH, XRP, to name a few) are working flawlessly.

@zimlokks I'm not saying here that your problem didn't boil down to a faulty USB cable, only that it looks like that's not the whole story.

@pydlv Re problem with Windows: interesting. My primary machine is indeed Windows. Will investigate, I can access a Linux PC fairly easily, I used it to hack around with the password manager's source code. Could you post a link to the Reddit thread here?

**Comment by pydlv** [comment]
@wkaluza Here you go: https://www.reddit.com/r/ledgerwallet/comments/fdnlm6/i_believe_it_is_critical_that_ledger_maintains/

**Comment by wkaluza** [comment]
Windows vs Linux: I can confirm that typing a password with FW v1.6 works when connected by USB to a Linux host machine. Choice of cable does not seem to be a factor - all the ones I have at my disposal function correctly with a Linux host and freeze the Ledger on Windows with 1.6. To reiterate, FW v1.5.5 **still works fine** regardless of cable or host OS, so I maintain something went badly wrong with the v1.6 firmware, SDK, or both. At least now I have a viable (if inconvenient) way to recover my most precious passwords if my backup Ledger ever malfunctions. Thank you @pydlv! 🏅 💐 🍾 

Food for thought: this bug would have much lower impact if the password manager app had the option to read passwords on the secure Ledger display instead of only typing them via USB. That would give users a fallback method to recover their password irrespective of USB- or OS-related shenanigans.

**Comment by fti7** [comment]
Same issue here. v1.6 - Windows 10 - Freezes when "entering" :-(

**Comment by zimlokks** [comment]
This issue is usually fixed just by swapping the USB cable with a known
good. Some USB cables for some unknown reason, will cause the Nano S to
freeze.

**Comment by fti7** [comment]
Tried with an other Cable. Also changed the Port in the PC. No luck :-( same issue...
What a bummer. They should fix that and integrated it better in an UI like the Trezor Wallet

**Comment by pydlv** [comment]
@fti7 Read issue history. I think we've established it's not a problem with the cable itself, but with how the operating system. Try on Linux or OS X. Still can't believe they haven't fixed this issue by now.

**Comment by TamtamHero** [comment]
Sorry about the delay, again.
Windows support is broken, but now that the app is available on Nano X, I can try to fix it. 
No ETA. 
First, I need a windows computer :')

**Comment by fti7** [comment]
Any Updates here? :-)

**Comment by TamtamHero** [comment]
Just merged https://github.com/LedgerHQ/app-passwords/pull/29
There's a lot of novelty, especially the possibility to backup the list of passwords with https://blog.ledger.com/passwords-backup/
(Sadly, it won't work with the version currently installed on your device (<1.0.0), but from now on updates will be smooth)
Be careful when upgrading the app, backup all the password names manually !
